baseurl: '/'
languageCode: en
paginate: 10
pluralizelisttitles: false
removePathAccents: true
title: Megapiksel (@mgpksl)
pygmentsStyle: native
summarylength: 30
relativeURLs: true
enableRobotsTXT: true
pygmentsCodeFences: true

social:
  twitter: mgpksl

params:
  emoji: ðŸ±â€ðŸ‘¤
  Description: >-
    Tempat saya ngomongin fotografi dan teknologi (internet, apps, windows, linux, smartphone), juga ngomongin gear, sosial, dan project. Tulisan bersifat opini.
  favicon : '/img/favicon.ico?v=0'
  logo : '/img/logo.svg'
  image: '/img/header.png'
  #notification: 'Hai, ada yang baru nih dari megapiksel.id,'
  #notiflink: '/projects/studioruang/'

# Disable categories since I don't use them.
taxonomies:
  tag: tags
  
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

menu:
  social:
    - name: Email
      weight: 1
      pre: '/img/email.svg'
      url: mailto:jaka@megapiksel.id
    - name: Podcast
      weight: 2
      pre: '/img/podcast.svg'
      url: https://anchor.fm/mgpksl
    - name: Twitter
      weigth: 3
      pre: '/img/twitter.svg'
      url: https://twitter.com/mgpksl
    - name: Instagram
      weight: 4
      pre: '/img/instagram.svg'
      url: https://www.instagram.com/mgpksl
